name: Run Tests
on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Rust Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - run: cargo test --all-features
